# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Yakitabu Backend CI

on:
  push:
    branches: [ staging, main ]
  pull_request:
    branches: [ staging, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: huaxk/postgis-action@v1
      with:
        postgresql version: '11'  # See https://https://hub.docker.com/r/mdillon/postgis for available versions, if it is not specified, use the default value 'latest'
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Test using unittest
      run: |
        python -m unittest
      env:
        TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
        DATABASE_URL: ${{ secrets.DATABASE_URI}}
        EMAIL: ${{ secrets.EMAIL }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        EMAIL: ${{ secrets.JWT_ACCESS_TOKEN_EXPIRES }}
        SECRET_KEY: ${{ secrets.JWT_REFRESH_TOKEN_EXPIRES }}
